[2025-08-05T19:18:33.219+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_medallon.cargar_a_bulk manual__2025-08-05T19:17:56.307282+00:00 [queued]>
[2025-08-05T19:18:33.253+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_medallon.cargar_a_bulk manual__2025-08-05T19:17:56.307282+00:00 [queued]>
[2025-08-05T19:18:33.254+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T19:18:33.307+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): cargar_a_bulk> on 2025-08-05 19:17:56.307282+00:00
[2025-08-05T19:18:33.312+0000] {standard_task_runner.py:60} INFO - Started process 171 to run task
[2025-08-05T19:18:33.317+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_medallon', 'cargar_a_bulk', 'manual__2025-08-05T19:17:56.307282+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_medallon_dag.py', '--cfg-path', '/tmp/tmpd6vzl9gj']
[2025-08-05T19:18:33.320+0000] {standard_task_runner.py:88} INFO - Job 249: Subtask cargar_a_bulk
[2025-08-05T19:18:33.411+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_medallon.cargar_a_bulk manual__2025-08-05T19:17:56.307282+00:00 [running]> on host 70eaa744a05c
[2025-08-05T19:18:33.594+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo.biasotto' AIRFLOW_CTX_DAG_ID='pipeline_medallon' AIRFLOW_CTX_TASK_ID='cargar_a_bulk' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T19:17:56.307282+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T19:17:56.307282+00:00'
[2025-08-05T19:18:33.597+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-05T19:18:33.599+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/minio_04_carga_a_transito.py']
[2025-08-05T19:18:33.611+0000] {subprocess.py:86} INFO - Output:
[2025-08-05T19:18:35.281+0000] {subprocess.py:93} INFO - Conectando a MinIO en minio:9000...
[2025-08-05T19:18:35.282+0000] {subprocess.py:93} INFO - Tablas bulk limpiadas correctamente antes de la carga.
[2025-08-05T19:18:35.282+0000] {subprocess.py:93} INFO - Cargando dim_cliente.parquet (4918 filas) a bulk_dim_cliente...
[2025-08-05T19:18:35.283+0000] {subprocess.py:93} INFO - 4918 filas cargadas en bulk_dim_cliente
[2025-08-05T19:18:35.283+0000] {subprocess.py:93} INFO - Cargando dim_producto.parquet (1894 filas) a bulk_dim_producto...
[2025-08-05T19:18:35.284+0000] {subprocess.py:93} INFO - 1894 filas cargadas en bulk_dim_producto
[2025-08-05T19:18:35.285+0000] {subprocess.py:93} INFO - Cargando fact_ventas.parquet (10003 filas) a bulk_fact_ventas...
[2025-08-05T19:18:35.294+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-05T19:18:35.294+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
[2025-08-05T19:18:35.295+0000] {subprocess.py:93} INFO -     self.dialect.do_executemany(
[2025-08-05T19:18:35.296+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
[2025-08-05T19:18:35.296+0000] {subprocess.py:93} INFO -     context._psycopg2_fetched_rows = xtras.execute_values(
[2025-08-05T19:18:35.297+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
[2025-08-05T19:18:35.297+0000] {subprocess.py:93} INFO -     cur.execute(b''.join(parts))
[2025-08-05T19:18:35.298+0000] {subprocess.py:93} INFO - psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "261,96"
[2025-08-05T19:18:35.298+0000] {subprocess.py:93} INFO - LINE 1: ...00:00'::timestamp, 'CG-12520', 'FUR-BO-10001798', '261,96', ...
[2025-08-05T19:18:35.299+0000] {subprocess.py:93} INFO -                                                              ^
[2025-08-05T19:18:35.300+0000] {subprocess.py:93} INFO - 
[2025-08-05T19:18:35.300+0000] {subprocess.py:93} INFO - 
[2025-08-05T19:18:35.301+0000] {subprocess.py:93} INFO - The above exception was the direct cause of the following exception:
[2025-08-05T19:18:35.302+0000] {subprocess.py:93} INFO - 
[2025-08-05T19:18:35.302+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-05T19:18:35.303+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/minio_04_carga_a_transito.py", line 70, in <module>
[2025-08-05T19:18:35.303+0000] {subprocess.py:93} INFO -     df.to_sql(tabla_pg, engine, if_exists="append", index=False, schema="public")
[2025-08-05T19:18:35.304+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
[2025-08-05T19:18:35.304+0000] {subprocess.py:93} INFO -     return sql.to_sql(
[2025-08-05T19:18:35.305+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
[2025-08-05T19:18:35.306+0000] {subprocess.py:93} INFO -     return pandas_sql.to_sql(
[2025-08-05T19:18:35.306+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
[2025-08-05T19:18:35.307+0000] {subprocess.py:93} INFO -     total_inserted = sql_engine.insert_records(
[2025-08-05T19:18:35.307+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
[2025-08-05T19:18:35.308+0000] {subprocess.py:93} INFO -     raise err
[2025-08-05T19:18:35.309+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
[2025-08-05T19:18:35.309+0000] {subprocess.py:93} INFO -     return table.insert(chunksize=chunksize, method=method)
[2025-08-05T19:18:35.310+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
[2025-08-05T19:18:35.310+0000] {subprocess.py:93} INFO -     num_inserted = exec_insert(conn, keys, chunk_iter)
[2025-08-05T19:18:35.311+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
[2025-08-05T19:18:35.311+0000] {subprocess.py:93} INFO -     result = conn.execute(self.table.insert(), data)
[2025-08-05T19:18:35.312+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
[2025-08-05T19:18:35.312+0000] {subprocess.py:93} INFO -     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
[2025-08-05T19:18:35.313+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
[2025-08-05T19:18:35.314+0000] {subprocess.py:93} INFO -     return connection._execute_clauseelement(
[2025-08-05T19:18:35.314+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
[2025-08-05T19:18:35.315+0000] {subprocess.py:93} INFO -     ret = self._execute_context(
[2025-08-05T19:18:35.315+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
[2025-08-05T19:18:35.316+0000] {subprocess.py:93} INFO -     self._handle_dbapi_exception(
[2025-08-05T19:18:35.317+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
[2025-08-05T19:18:35.317+0000] {subprocess.py:93} INFO -     util.raise_(
[2025-08-05T19:18:35.318+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[2025-08-05T19:18:35.319+0000] {subprocess.py:93} INFO -     raise exception
[2025-08-05T19:18:35.319+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
[2025-08-05T19:18:35.320+0000] {subprocess.py:93} INFO -     self.dialect.do_executemany(
[2025-08-05T19:18:35.321+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
[2025-08-05T19:18:35.321+0000] {subprocess.py:93} INFO -     context._psycopg2_fetched_rows = xtras.execute_values(
[2025-08-05T19:18:35.322+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
[2025-08-05T19:18:35.322+0000] {subprocess.py:93} INFO -     cur.execute(b''.join(parts))
[2025-08-05T19:18:35.323+0000] {subprocess.py:93} INFO - sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type numeric: "261,96"
[2025-08-05T19:18:35.324+0000] {subprocess.py:93} INFO - LINE 1: ...00:00'::timestamp, 'CG-12520', 'FUR-BO-10001798', '261,96', ...
[2025-08-05T19:18:35.324+0000] {subprocess.py:93} INFO -                                                              ^
[2025-08-05T19:18:35.325+0000] {subprocess.py:93} INFO - 
[2025-08-05T19:18:35.326+0000] {subprocess.py:93} INFO - [SQL: INSERT INTO public.bulk_fact_ventas (order_id, order_date, ship_date, customer_id, product_id, sales, quantity, discount, profit) VALUES (%(order_id)s, %(order_date)s, %(ship_date)s, %(customer_id)s, %(product_id)s, %(sales)s, %(quantity)s, %(discount)s, %(profit)s)]
[2025-08-05T19:18:35.326+0000] {subprocess.py:93} INFO - [parameters: ({'order_id': 'CA-2016-152156', 'order_date': datetime.datetime(2016, 11, 8, 0, 0), 'ship_date': datetime.datetime(2016, 11, 11, 0, 0), 'customer_id': 'CG-12520', 'product_id': 'FUR-BO-10001798', 'sales': '261,96', 'quantity': 2, 'discount': '0', 'profit': '41,9136'}, {'order_id': 'CA-2016-152156', 'order_date': datetime.datetime(2016, 11, 8, 0, 0), 'ship_date': datetime.datetime(2016, 11, 11, 0, 0), 'customer_id': 'CG-12520', 'product_id': 'FUR-CH-10000454', 'sales': '731,94', 'quantity': 3, 'discount': '0', 'profit': '219,582'}, {'order_id': 'CA-2016-138688', 'order_date': datetime.datetime(2016, 6, 12, 0, 0), 'ship_date': datetime.datetime(2016, 6, 16, 0, 0), 'customer_id': 'DV-13045', 'product_id': 'OFF-LA-10000240', 'sales': '14,62', 'quantity': 2, 'discount': '0', 'profit': '6,8714'}, {'order_id': 'US-2015-108966', 'order_date': datetime.datetime(2015, 10, 11, 0, 0), 'ship_date': datetime.datetime(2015, 10, 18, 0, 0), 'customer_id': 'SO-20335', 'product_id': 'FUR-TA-10000577', 'sales': '957,5775', 'quantity': 5, 'discount': '0,45', 'profit': '-383,031'}, {'order_id': 'US-2015-108966', 'order_date': datetime.datetime(2015, 10, 11, 0, 0), 'ship_date': datetime.datetime(2015, 10, 18, 0, 0), 'customer_id': 'SO-20335', 'product_id': 'OFF-ST-10000760', 'sales': '22,368', 'quantity': 2, 'discount': '0,2', 'profit': '2,5164'}, {'order_id': 'CA-2014-115812', 'order_date': datetime.datetime(2014, 6, 9, 0, 0), 'ship_date': datetime.datetime(2014, 6, 14, 0, 0), 'customer_id': 'BH-11710', 'product_id': 'FUR-FU-10001487', 'sales': '48,86', 'quantity': 7, 'discount': '0', 'profit': '14,1694'}, {'order_id': 'CA-2014-115812', 'order_date': datetime.datetime(2014, 6, 9, 0, 0), 'ship_date': datetime.datetime(2014, 6, 14, 0, 0), 'customer_id': 'BH-11710', 'product_id': 'OFF-AR-10002833', 'sales': '7,28', 'quantity': 4, 'discount': '0', 'profit': '1,9656'}, {'order_id': 'CA-2014-115812', 'order_date': datetime.datetime(2014, 6, 9, 0, 0), 'ship_date': datetime.datetime(2014, 6, 14, 0, 0), 'customer_id': 'BH-11710', 'product_id': 'TEC-PH-10002275', 'sales': '907,152', 'quantity': 6, 'discount': '0,2', 'profit': '90,7152'}  ... displaying 10 of 10003 total bound parameter sets ...  {'order_id': 'CA-2017-119914', 'order_date': datetime.datetime(2032, 5, 4, 0, 0), 'ship_date': datetime.datetime(2033, 5, 9, 0, 0), 'customer_id': 'AP-10599', 'product_id': 'OFF-AP-10002684', 'sales': '243,16', 'quantity': 2, 'discount': '0', 'profit': '72,948'}, {'order_id': 'CA-2017-119914', 'order_date': datetime.datetime(2032, 5, 4, 0, 0), 'ship_date': datetime.datetime(2033, 5, 9, 0, 0), 'customer_id': 'AP-10888', 'product_id': 'OFF-AP-10002684', 'sales': '243,16', 'quantity': 2, 'discount': '0', 'profit': '72,948'})]
[2025-08-05T19:18:35.327+0000] {subprocess.py:93} INFO - (Background on this error at: https://sqlalche.me/e/14/9h9h)
[2025-08-05T19:18:35.442+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-05T19:18:35.459+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-05T19:18:35.463+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_medallon, task_id=cargar_a_bulk, execution_date=20250805T191756, start_date=20250805T191833, end_date=20250805T191835
[2025-08-05T19:18:35.533+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 249 for task cargar_a_bulk (Bash command failed. The command returned a non-zero exit code 1.; 171)
[2025-08-05T19:18:35.579+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T19:18:35.615+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
