[2025-07-31T14:50:04.855+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_medallon.crea_stored_procedure manual__2025-07-31T14:49:48.812055+00:00 [queued]>
[2025-07-31T14:50:04.971+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_medallon.crea_stored_procedure manual__2025-07-31T14:49:48.812055+00:00 [queued]>
[2025-07-31T14:50:04.971+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-31T14:50:05.022+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): crea_stored_procedure> on 2025-07-31 14:49:48.812055+00:00
[2025-07-31T14:50:05.026+0000] {standard_task_runner.py:60} INFO - Started process 77 to run task
[2025-07-31T14:50:05.032+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_medallon', 'crea_stored_procedure', 'manual__2025-07-31T14:49:48.812055+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_medallon_dag.py', '--cfg-path', '/tmp/tmpvc3glan7']
[2025-07-31T14:50:05.034+0000] {standard_task_runner.py:88} INFO - Job 84: Subtask crea_stored_procedure
[2025-07-31T14:50:05.143+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_medallon.crea_stored_procedure manual__2025-07-31T14:49:48.812055+00:00 [running]> on host 70eaa744a05c
[2025-07-31T14:50:05.290+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo.biasotto' AIRFLOW_CTX_DAG_ID='pipeline_medallon' AIRFLOW_CTX_TASK_ID='crea_stored_procedure' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T14:49:48.812055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T14:49:48.812055+00:00'
[2025-07-31T14:50:05.291+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-31T14:50:05.293+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/03_crea_stored_procedure.py']
[2025-07-31T14:50:05.300+0000] {subprocess.py:86} INFO - Output:
[2025-07-31T14:50:05.329+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/airflow/scripts/03_crea_stored_procedure.py': [Errno 2] No such file or directory
[2025-07-31T14:50:05.333+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-31T14:50:05.348+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-31T14:50:05.352+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_medallon, task_id=crea_stored_procedure, execution_date=20250731T144948, start_date=20250731T145004, end_date=20250731T145005
[2025-07-31T14:50:05.390+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 84 for task crea_stored_procedure (Bash command failed. The command returned a non-zero exit code 2.; 77)
[2025-07-31T14:50:05.405+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-31T14:50:05.441+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
