[2025-07-30T21:18:07.008+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_medallon.crea_esquema_publico manual__2025-07-30T21:12:57.467909+00:00 [queued]>
[2025-07-30T21:18:07.102+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_medallon.crea_esquema_publico manual__2025-07-30T21:12:57.467909+00:00 [queued]>
[2025-07-30T21:18:07.103+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-30T21:18:07.151+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): crea_esquema_publico> on 2025-07-30 21:12:57.467909+00:00
[2025-07-30T21:18:07.155+0000] {standard_task_runner.py:60} INFO - Started process 87 to run task
[2025-07-30T21:18:07.161+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_medallon', 'crea_esquema_publico', 'manual__2025-07-30T21:12:57.467909+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_medallon_dag.py', '--cfg-path', '/tmp/tmp3fiakt6p']
[2025-07-30T21:18:07.164+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask crea_esquema_publico
[2025-07-30T21:18:07.332+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_medallon.crea_esquema_publico manual__2025-07-30T21:12:57.467909+00:00 [running]> on host 70eaa744a05c
[2025-07-30T21:18:07.510+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo.biasotto' AIRFLOW_CTX_DAG_ID='pipeline_medallon' AIRFLOW_CTX_TASK_ID='crea_esquema_publico' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T21:12:57.467909+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T21:12:57.467909+00:00'
[2025-07-30T21:18:07.512+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-30T21:18:07.514+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/01_crea_esquema_publico.py']
[2025-07-30T21:18:07.524+0000] {subprocess.py:86} INFO - Output:
[2025-07-30T21:18:07.564+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/airflow/scripts/01_crea_esquema_publico.py': [Errno 2] No such file or directory
[2025-07-30T21:18:07.568+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-30T21:18:07.590+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-30T21:18:07.596+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=pipeline_medallon, task_id=crea_esquema_publico, execution_date=20250730T211257, start_date=20250730T211807, end_date=20250730T211807
[2025-07-30T21:18:07.638+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task crea_esquema_publico (Bash command failed. The command returned a non-zero exit code 2.; 87)
[2025-07-30T21:18:07.656+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-30T21:18:07.703+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
