[2025-07-30T21:26:20.566+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_medallon.crea_esquema_staging manual__2025-07-30T21:21:07+00:00 [queued]>
[2025-07-30T21:26:20.687+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_medallon.crea_esquema_staging manual__2025-07-30T21:21:07+00:00 [queued]>
[2025-07-30T21:26:20.687+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-30T21:26:20.725+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): crea_esquema_staging> on 2025-07-30 21:21:07+00:00
[2025-07-30T21:26:20.732+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_medallon', 'crea_esquema_staging', 'manual__2025-07-30T21:21:07+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_medallon_dag.py', '--cfg-path', '/tmp/tmpo0vmwuv7']
[2025-07-30T21:26:20.730+0000] {standard_task_runner.py:60} INFO - Started process 156 to run task
[2025-07-30T21:26:20.734+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask crea_esquema_staging
[2025-07-30T21:26:20.814+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_medallon.crea_esquema_staging manual__2025-07-30T21:21:07+00:00 [running]> on host 70eaa744a05c
[2025-07-30T21:26:20.924+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo.biasotto' AIRFLOW_CTX_DAG_ID='pipeline_medallon' AIRFLOW_CTX_TASK_ID='crea_esquema_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T21:21:07+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T21:21:07+00:00'
[2025-07-30T21:26:20.925+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-30T21:26:20.926+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/02_crea_esquema_staging.py']
[2025-07-30T21:26:20.932+0000] {subprocess.py:86} INFO - Output:
[2025-07-30T21:26:21.011+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-30T21:26:21.012+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/02_crea_esquema_staging.py", line 9, in <module>
[2025-07-30T21:26:21.012+0000] {subprocess.py:93} INFO -     conn = psycopg2.connect(
[2025-07-30T21:26:21.013+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-07-30T21:26:21.013+0000] {subprocess.py:93} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-07-30T21:26:21.014+0000] {subprocess.py:93} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-07-30T21:26:21.014+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-07-30T21:26:21.015+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-07-30T21:26:21.016+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-07-30T21:26:21.016+0000] {subprocess.py:93} INFO - 
[2025-07-30T21:26:21.017+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-30T21:26:21.035+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-30T21:26:21.039+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=pipeline_medallon, task_id=crea_esquema_staging, execution_date=20250730T212107, start_date=20250730T212620, end_date=20250730T212621
[2025-07-30T21:26:21.102+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task crea_esquema_staging (Bash command failed. The command returned a non-zero exit code 1.; 156)
[2025-07-30T21:26:21.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-30T21:26:21.141+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
