[2025-07-31T14:08:13.818+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_medallon.ejecutar_merge manual__2025-07-31T14:07:22.859095+00:00 [queued]>
[2025-07-31T14:08:13.932+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_medallon.ejecutar_merge manual__2025-07-31T14:07:22.859095+00:00 [queued]>
[2025-07-31T14:08:13.933+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-31T14:08:13.987+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): ejecutar_merge> on 2025-07-31 14:07:22.859095+00:00
[2025-07-31T14:08:13.993+0000] {standard_task_runner.py:60} INFO - Started process 224 to run task
[2025-07-31T14:08:13.997+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_medallon', 'ejecutar_merge', 'manual__2025-07-31T14:07:22.859095+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_medallon_dag.py', '--cfg-path', '/tmp/tmpyeinn3uc']
[2025-07-31T14:08:13.999+0000] {standard_task_runner.py:88} INFO - Job 79: Subtask ejecutar_merge
[2025-07-31T14:08:14.091+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_medallon.ejecutar_merge manual__2025-07-31T14:07:22.859095+00:00 [running]> on host 70eaa744a05c
[2025-07-31T14:08:14.237+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo.biasotto' AIRFLOW_CTX_DAG_ID='pipeline_medallon' AIRFLOW_CTX_TASK_ID='ejecutar_merge' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T14:07:22.859095+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T14:07:22.859095+00:00'
[2025-07-31T14:08:14.238+0000] {sql.py:276} INFO - Executing: CALL merge_bulk_to_final();
[2025-07-31T14:08:14.252+0000] {base.py:83} INFO - Using connection ID 'postgres_medallon' for task execution.
[2025-07-31T14:08:14.358+0000] {base.py:83} INFO - Using connection ID 'postgres_medallon' for task execution.
[2025-07-31T14:08:14.395+0000] {sql.py:450} INFO - Running statement: CALL merge_bulk_to_final();, parameters: None
[2025-07-31T14:08:14.441+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFunction: function replace(numeric, unknown, unknown) does not exist
LINE 20:         REPLACE(sales, ',', '.')::numeric,
                 ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  INSERT INTO staging.fact_ventas (
        taligent_id,
        order_id,
        order_date,
        ship_date,
        customer_id,
        product_id,
        sales,
        quantity,
        discount,
        profit
    )
    SELECT DISTINCT ON (order_id || '-' || product_id)
        order_id || '-' || product_id AS taligent_id,
        order_id,
        order_date::date,
        ship_date::date,
        customer_id,
        product_id,
        REPLACE(sales, ',', '.')::numeric,
        quantity::int,
        REPLACE(discount, ',', '.')::numeric,
        REPLACE(profit, ',', '.')::numeric
    FROM public.bulk_fact_ventas
    ORDER BY order_id || '-' || product_id
    ON CONFLICT (taligent_id) DO UPDATE
    SET order_date  = EXCLUDED.order_date,
        ship_date   = EXCLUDED.ship_date,
        customer_id = EXCLUDED.customer_id,
        product_id  = EXCLUDED.product_id,
        sales       = EXCLUDED.sales,
        quantity    = EXCLUDED.quantity,
        discount    = EXCLUDED.discount,
        profit      = EXCLUDED.profit
CONTEXT:  PL/pgSQL function merge_bulk_to_final() line 34 at SQL statement

[2025-07-31T14:08:14.454+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_medallon, task_id=ejecutar_merge, execution_date=20250731T140722, start_date=20250731T140813, end_date=20250731T140814
[2025-07-31T14:08:14.492+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 79 for task ejecutar_merge (function replace(numeric, unknown, unknown) does not exist
LINE 20:         REPLACE(sales, ',', '.')::numeric,
                 ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  INSERT INTO staging.fact_ventas (
        taligent_id,
        order_id,
        order_date,
        ship_date,
        customer_id,
        product_id,
        sales,
        quantity,
        discount,
        profit
    )
    SELECT DISTINCT ON (order_id || '-' || product_id)
        order_id || '-' || product_id AS taligent_id,
        order_id,
        order_date::date,
        ship_date::date,
        customer_id,
        product_id,
        REPLACE(sales, ',', '.')::numeric,
        quantity::int,
        REPLACE(discount, ',', '.')::numeric,
        REPLACE(profit, ',', '.')::numeric
    FROM public.bulk_fact_ventas
    ORDER BY order_id || '-' || product_id
    ON CONFLICT (taligent_id) DO UPDATE
    SET order_date  = EXCLUDED.order_date,
        ship_date   = EXCLUDED.ship_date,
        customer_id = EXCLUDED.customer_id,
        product_id  = EXCLUDED.product_id,
        sales       = EXCLUDED.sales,
        quantity    = EXCLUDED.quantity,
        discount    = EXCLUDED.discount,
        profit      = EXCLUDED.profit
CONTEXT:  PL/pgSQL function merge_bulk_to_final() line 34 at SQL statement
; 224)
[2025-07-31T14:08:14.532+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-31T14:08:14.557+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
