[2025-08-04T15:40:19.017+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_medallon.cargar_a_bulk manual__2025-08-04T15:39:36+00:00 [queued]>
[2025-08-04T15:40:19.038+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_medallon.cargar_a_bulk manual__2025-08-04T15:39:36+00:00 [queued]>
[2025-08-04T15:40:19.038+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-04T15:40:19.104+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): cargar_a_bulk> on 2025-08-04 15:39:36+00:00
[2025-08-04T15:40:19.109+0000] {standard_task_runner.py:60} INFO - Started process 181 to run task
[2025-08-04T15:40:19.114+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_medallon', 'cargar_a_bulk', 'manual__2025-08-04T15:39:36+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_medallon_dag.py', '--cfg-path', '/tmp/tmpiumtuiqe']
[2025-08-04T15:40:19.116+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask cargar_a_bulk
[2025-08-04T15:40:19.229+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_medallon.cargar_a_bulk manual__2025-08-04T15:39:36+00:00 [running]> on host 70eaa744a05c
[2025-08-04T15:40:19.388+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo.biasotto' AIRFLOW_CTX_DAG_ID='pipeline_medallon' AIRFLOW_CTX_TASK_ID='cargar_a_bulk' AIRFLOW_CTX_EXECUTION_DATE='2025-08-04T15:39:36+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-04T15:39:36+00:00'
[2025-08-04T15:40:19.389+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-04T15:40:19.390+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/minio_04_carga_a_transito.py']
[2025-08-04T15:40:19.397+0000] {subprocess.py:86} INFO - Output:
[2025-08-04T15:40:21.000+0000] {subprocess.py:93} INFO - Conectando a MinIO en minio:9000...
[2025-08-04T15:40:21.001+0000] {subprocess.py:93} INFO - Tablas bulk limpiadas correctamente antes de la carga.
[2025-08-04T15:40:21.001+0000] {subprocess.py:93} INFO - Cargando dim_cliente.parquet (4910 filas) a bulk_dim_cliente...
[2025-08-04T15:40:21.002+0000] {subprocess.py:93} INFO -    ðŸ”¹ bulk_dim_cliente: 4910 â†’ 793 filas tras limpiar nulos y duplicados en customer_id.
[2025-08-04T15:40:21.003+0000] {subprocess.py:93} INFO - 793 filas cargadas en bulk_dim_cliente
[2025-08-04T15:40:21.004+0000] {subprocess.py:93} INFO - Cargando dim_producto.parquet (1894 filas) a bulk_dim_producto...
[2025-08-04T15:40:21.004+0000] {subprocess.py:93} INFO -    ðŸ”¹ bulk_dim_producto: 1894 â†’ 1862 filas tras limpiar nulos y duplicados en product_id.
[2025-08-04T15:40:21.006+0000] {subprocess.py:93} INFO - 1862 filas cargadas en bulk_dim_producto
[2025-08-04T15:40:21.007+0000] {subprocess.py:93} INFO - Cargando fact_ventas.parquet (9994 filas) a bulk_fact_ventas...
[2025-08-04T15:40:21.008+0000] {subprocess.py:93} INFO -    ðŸ”¹ bulk_fact_ventas: 9994 â†’ 9986 filas tras limpiar nulos y duplicados en (order_id, product_id).
[2025-08-04T15:40:21.014+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-04T15:40:21.015+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
[2025-08-04T15:40:21.016+0000] {subprocess.py:93} INFO -     self.dialect.do_executemany(
[2025-08-04T15:40:21.017+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
[2025-08-04T15:40:21.017+0000] {subprocess.py:93} INFO -     context._psycopg2_fetched_rows = xtras.execute_values(
[2025-08-04T15:40:21.018+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
[2025-08-04T15:40:21.019+0000] {subprocess.py:93} INFO -     cur.execute(b''.join(parts))
[2025-08-04T15:40:21.020+0000] {subprocess.py:93} INFO - psycopg2.errors.NotNullViolation: null value in column "taligent_id" of relation "bulk_fact_ventas" violates not-null constraint
[2025-08-04T15:40:21.021+0000] {subprocess.py:93} INFO - DETAIL:  Failing row contains (null, CA-2016-152156, 2016-11-08, 2016-11-11, CG-12520, FUR-BO-10001798, 261.96, 2, 0.0, 41.9136).
[2025-08-04T15:40:21.021+0000] {subprocess.py:93} INFO - 
[2025-08-04T15:40:21.022+0000] {subprocess.py:93} INFO - 
[2025-08-04T15:40:21.022+0000] {subprocess.py:93} INFO - The above exception was the direct cause of the following exception:
[2025-08-04T15:40:21.023+0000] {subprocess.py:93} INFO - 
[2025-08-04T15:40:21.024+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-04T15:40:21.025+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/minio_04_carga_a_transito.py", line 105, in <module>
[2025-08-04T15:40:21.026+0000] {subprocess.py:93} INFO -     df.to_sql(tabla_pg, engine, if_exists="append", index=False, schema="public")
[2025-08-04T15:40:21.027+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
[2025-08-04T15:40:21.027+0000] {subprocess.py:93} INFO -     return sql.to_sql(
[2025-08-04T15:40:21.028+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
[2025-08-04T15:40:21.029+0000] {subprocess.py:93} INFO -     return pandas_sql.to_sql(
[2025-08-04T15:40:21.029+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
[2025-08-04T15:40:21.030+0000] {subprocess.py:93} INFO -     total_inserted = sql_engine.insert_records(
[2025-08-04T15:40:21.030+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
[2025-08-04T15:40:21.031+0000] {subprocess.py:93} INFO -     raise err
[2025-08-04T15:40:21.031+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
[2025-08-04T15:40:21.032+0000] {subprocess.py:93} INFO -     return table.insert(chunksize=chunksize, method=method)
[2025-08-04T15:40:21.032+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
[2025-08-04T15:40:21.033+0000] {subprocess.py:93} INFO -     num_inserted = exec_insert(conn, keys, chunk_iter)
[2025-08-04T15:40:21.034+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
[2025-08-04T15:40:21.035+0000] {subprocess.py:93} INFO -     result = conn.execute(self.table.insert(), data)
[2025-08-04T15:40:21.036+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
[2025-08-04T15:40:21.036+0000] {subprocess.py:93} INFO -     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
[2025-08-04T15:40:21.037+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
[2025-08-04T15:40:21.037+0000] {subprocess.py:93} INFO -     return connection._execute_clauseelement(
[2025-08-04T15:40:21.038+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
[2025-08-04T15:40:21.038+0000] {subprocess.py:93} INFO -     ret = self._execute_context(
[2025-08-04T15:40:21.039+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
[2025-08-04T15:40:21.039+0000] {subprocess.py:93} INFO -     self._handle_dbapi_exception(
[2025-08-04T15:40:21.040+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
[2025-08-04T15:40:21.040+0000] {subprocess.py:93} INFO -     util.raise_(
[2025-08-04T15:40:21.041+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[2025-08-04T15:40:21.042+0000] {subprocess.py:93} INFO -     raise exception
[2025-08-04T15:40:21.043+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
[2025-08-04T15:40:21.043+0000] {subprocess.py:93} INFO -     self.dialect.do_executemany(
[2025-08-04T15:40:21.044+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
[2025-08-04T15:40:21.045+0000] {subprocess.py:93} INFO -     context._psycopg2_fetched_rows = xtras.execute_values(
[2025-08-04T15:40:21.046+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
[2025-08-04T15:40:21.047+0000] {subprocess.py:93} INFO -     cur.execute(b''.join(parts))
[2025-08-04T15:40:21.047+0000] {subprocess.py:93} INFO - sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "taligent_id" of relation "bulk_fact_ventas" violates not-null constraint
[2025-08-04T15:40:21.048+0000] {subprocess.py:93} INFO - DETAIL:  Failing row contains (null, CA-2016-152156, 2016-11-08, 2016-11-11, CG-12520, FUR-BO-10001798, 261.96, 2, 0.0, 41.9136).
[2025-08-04T15:40:21.048+0000] {subprocess.py:93} INFO - 
[2025-08-04T15:40:21.049+0000] {subprocess.py:93} INFO - [SQL: INSERT INTO public.bulk_fact_ventas (order_id, order_date, ship_date, customer_id, product_id, sales, quantity, discount, profit) VALUES (%(order_id)s, %(order_date)s, %(ship_date)s, %(customer_id)s, %(product_id)s, %(sales)s, %(quantity)s, %(discount)s, %(profit)s)]
[2025-08-04T15:40:21.049+0000] {subprocess.py:93} INFO - [parameters: ({'order_id': 'CA-2016-152156', 'order_date': datetime.datetime(2016, 11, 8, 0, 0), 'ship_date': datetime.datetime(2016, 11, 11, 0, 0), 'customer_id': 'CG-12520', 'product_id': 'FUR-BO-10001798', 'sales': 261.96, 'quantity': 2, 'discount': 0.0, 'profit': 41.9136}, {'order_id': 'CA-2016-152156', 'order_date': datetime.datetime(2016, 11, 8, 0, 0), 'ship_date': datetime.datetime(2016, 11, 11, 0, 0), 'customer_id': 'CG-12520', 'product_id': 'FUR-CH-10000454', 'sales': 731.94, 'quantity': 3, 'discount': 0.0, 'profit': 219.582}, {'order_id': 'CA-2016-138688', 'order_date': datetime.datetime(2016, 6, 12, 0, 0), 'ship_date': datetime.datetime(2016, 6, 16, 0, 0), 'customer_id': 'DV-13045', 'product_id': 'OFF-LA-10000240', 'sales': 14.62, 'quantity': 2, 'discount': 0.0, 'profit': 6.8714}, {'order_id': 'US-2015-108966', 'order_date': datetime.datetime(2015, 10, 11, 0, 0), 'ship_date': datetime.datetime(2015, 10, 18, 0, 0), 'customer_id': 'SO-20335', 'product_id': 'FUR-TA-10000577', 'sales': 957.5775, 'quantity': 5, 'discount': 0.45, 'profit': -383.031}, {'order_id': 'US-2015-108966', 'order_date': datetime.datetime(2015, 10, 11, 0, 0), 'ship_date': datetime.datetime(2015, 10, 18, 0, 0), 'customer_id': 'SO-20335', 'product_id': 'OFF-ST-10000760', 'sales': 22.368, 'quantity': 2, 'discount': 0.2, 'profit': 2.5164}, {'order_id': 'CA-2014-115812', 'order_date': datetime.datetime(2014, 6, 9, 0, 0), 'ship_date': datetime.datetime(2014, 6, 14, 0, 0), 'customer_id': 'BH-11710', 'product_id': 'FUR-FU-10001487', 'sales': 48.86, 'quantity': 7, 'discount': 0.0, 'profit': 14.1694}, {'order_id': 'CA-2014-115812', 'order_date': datetime.datetime(2014, 6, 9, 0, 0), 'ship_date': datetime.datetime(2014, 6, 14, 0, 0), 'customer_id': 'BH-11710', 'product_id': 'OFF-AR-10002833', 'sales': 7.28, 'quantity': 4, 'discount': 0.0, 'profit': 1.9656}, {'order_id': 'CA-2014-115812', 'order_date': datetime.datetime(2014, 6, 9, 0, 0), 'ship_date': datetime.datetime(2014, 6, 14, 0, 0), 'customer_id': 'BH-11710', 'product_id': 'TEC-PH-10002275', 'sales': 907.152, 'quantity': 6, 'discount': 0.2, 'profit': 90.7152}  ... displaying 10 of 9986 total bound parameter sets ...  {'order_id': 'CA-2017-121258', 'order_date': datetime.datetime(2017, 2, 26, 0, 0), 'ship_date': datetime.datetime(2017, 3, 3, 0, 0), 'customer_id': 'DB-13060', 'product_id': 'OFF-PA-10004041', 'sales': 29.6, 'quantity': 4, 'discount': 0.0, 'profit': 13.32}, {'order_id': 'CA-2017-119914', 'order_date': datetime.datetime(2017, 5, 4, 0, 0), 'ship_date': datetime.datetime(2017, 5, 9, 0, 0), 'customer_id': 'CC-12220', 'product_id': 'OFF-AP-10002684', 'sales': 243.16, 'quantity': 2, 'discount': 0.0, 'profit': 72.948})]
[2025-08-04T15:40:21.050+0000] {subprocess.py:93} INFO - (Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-08-04T15:40:21.174+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-04T15:40:21.191+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-04T15:40:21.197+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_medallon, task_id=cargar_a_bulk, execution_date=20250804T153936, start_date=20250804T154019, end_date=20250804T154021
[2025-08-04T15:40:21.260+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 190 for task cargar_a_bulk (Bash command failed. The command returned a non-zero exit code 1.; 181)
[2025-08-04T15:40:21.295+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-04T15:40:21.326+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
